CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name TEXT DEFAULT NULL,
  email TEXT NOT NULL UNIQUE,
  email_verified_at TIMESTAMP DEFAULT NULL,
  password TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);